### ISSUE TITLE
Cannot run command - cannot require files

### ISSUE THREAD

**Issue by albinscode** [SchweizerischeBundesbahnen/hibernate_hbm2annotation#25]
**Describe the bug**

When running application I got a require_once error.

**To Reproduce**

I run the following command on an ubuntu 18.04 system with php 7.2 :

~~~
cd /root/git/
git clone https://github.com/SchweizerischeBundesbahnen/hibernate_hbm2annotation
cd hibernate_hbm2annotation
php migrate.php
~~~

Then I got the following error : 

~~~
PHP Warning:  require_once(/root/git/hibernate_hbm2annotation./Hbm/Converter.php): failed to open stream: No such file or directory in /root/git/hibernate_hbm2annotation/migrate.php on line 2
~~~

**Expected behavior:**

The command shall run without error.

By inspecting the code I see that the line 2 is `require_once __DIR__ . './Hbm/Converter.php'`.

That will lead to be evaluated to `'/root/git/hibernate_hbm2annotation' .  './Hbm/Converter.php'` as described in the error.

As described in the php manual, `__DIR__` won't add a slash at the end except when in `/` root directory.

See http://php.net/manual/en/language.constants.predefined.php.

Do I miss a configuration tip?

**Comment by martyschaer** [comment]
Reading the documentation I wonder why it worked on our systems. We only tested this on Windows 10 machines so far.

But it also works when it's done "the right way", according to the docs, so I'll change our `require_once`s accordingly.

Thanks for the report @albinscode

**Comment by martyschaer** [comment]
I've changed the `require_once`-statements where I thought they might cause problems.

Could you test the following commit? [321b6432c41202cbd63dda0ef913e667a76aa16a](https://github.com/SchweizerischeBundesbahnen/hibernate_hbm2annotation/commit/321b6432c41202cbd63dda0ef913e667a76aa16a)

**Comment by albinscode** [comment]
Yes, now that's fixed ;) Thank you.

I tested the previous version on Windows 10 and it was raising the same error.

**Comment by martyschaer** [comment]
That's very weird, but I'm glad it's working now. I'll merge this into **develop** now.

**Comment by albinscode** [comment]
Thanks a lot!

**Comment by martyschaer** [comment]
That would be great, I'm interested how it works for you, because you're the first external person (that we know of) to use this script.
